// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum DeviceType {
  smartphone,
  watch,
  tablet,
  other,
}

enum DeviceState {
  disconnected,
  connecting,
  connected,
  ranging,
}

class UwbDevice {
  UwbDevice({
    this.id,
    this.name,
    this.deviceType,
    this.state,
    this.distance,
  });

  String? id;

  String? name;

  DeviceType? deviceType;

  DeviceState? state;

  double? distance;

  Object encode() {
    return <Object?>[
      id,
      name,
      deviceType?.index,
      state?.index,
      distance,
    ];
  }

  static UwbDevice decode(Object result) {
    result as List<Object?>;
    return UwbDevice(
      id: result[0] as String?,
      name: result[1] as String?,
      deviceType: result[2] != null
          ? DeviceType.values[result[2]! as int]
          : null,
      state: result[3] != null
          ? DeviceState.values[result[3]! as int]
          : null,
      distance: result[4] as double?,
    );
  }
}

class _UwbHostApiCodec extends StandardMessageCodec {
  const _UwbHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is UwbDevice) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return UwbDevice.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class UwbHostApi {
  /// Constructor for [UwbHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UwbHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _UwbHostApiCodec();

  Future<bool> isUwbSupported() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.pod_finder_pro_178.UwbHostApi.isUwbSupported';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<void> startDiscovery(String deviceName) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.pod_finder_pro_178.UwbHostApi.startDiscovery';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[deviceName]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopDiscovery() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.pod_finder_pro_178.UwbHostApi.stopDiscovery';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startRanging(UwbDevice device) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.pod_finder_pro_178.UwbHostApi.startRanging';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[device]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopRanging(UwbDevice device) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.pod_finder_pro_178.UwbHostApi.stopRanging';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[device]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> handleConnectionRequest(UwbDevice device, bool accept) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.pod_finder_pro_178.UwbHostApi.handleConnectionRequest';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[device, accept]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

class _UwbFlutterApiCodec extends StandardMessageCodec {
  const _UwbFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is UwbDevice) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return UwbDevice.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class UwbFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _UwbFlutterApiCodec();

  void onDiscoveryDeviceFound(UwbDevice device);

  void onDiscoveryDeviceLost(UwbDevice device);

  void onDiscoveryDeviceConnected(UwbDevice device);

  void onDiscoveryDeviceDisconnected(UwbDevice device);

  void onDiscoveryDeviceRejected(UwbDevice device);

  void onDiscoveryConnectionRequestReceived(UwbDevice device);

  void onUwbSessionStarted(UwbDevice device);

  void onUwbSessionDisconnected(UwbDevice device);

  static void setup(UwbFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceFound', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceFound was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceFound was null, expected non-null UwbDevice.');
          try {
            api.onDiscoveryDeviceFound(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceLost', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceLost was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceLost was null, expected non-null UwbDevice.');
          try {
            api.onDiscoveryDeviceLost(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceConnected', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceConnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceConnected was null, expected non-null UwbDevice.');
          try {
            api.onDiscoveryDeviceConnected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceDisconnected', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceDisconnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceDisconnected was null, expected non-null UwbDevice.');
          try {
            api.onDiscoveryDeviceDisconnected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceRejected', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceRejected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryDeviceRejected was null, expected non-null UwbDevice.');
          try {
            api.onDiscoveryDeviceRejected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryConnectionRequestReceived', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryConnectionRequestReceived was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onDiscoveryConnectionRequestReceived was null, expected non-null UwbDevice.');
          try {
            api.onDiscoveryConnectionRequestReceived(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onUwbSessionStarted', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onUwbSessionStarted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onUwbSessionStarted was null, expected non-null UwbDevice.');
          try {
            api.onUwbSessionStarted(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onUwbSessionDisconnected', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onUwbSessionDisconnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.pod_finder_pro_178.UwbFlutterApi.onUwbSessionDisconnected was null, expected non-null UwbDevice.');
          try {
            api.onUwbSessionDisconnected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
