name: pod_finder_pro_178
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_svg: ^2.0.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  flutter_blue_plus: ^1.35.3
  collection: ^1.0.0
  flutter_animate: ^4.5.2
  ffi: ^2.0.0
  meta: ^1.0.0
  plugin_platform_interface: ^2.0.2
  geolocator: ^10.1.0
  apple_maps_flutter: ^1.4.0
  screenshot: 3.0.0
  intl: ^0.19.0
  uwb:
    path: ./uwb_plugin
  apphud: 2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.8
  pigeon: ^17.2.0
  pigeon_build_runner: 1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vector/
    - assets/fonts/
  fonts:
    - family: SfPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf